# Generated by Django 4.2.2 on 2023-06-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mall", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "상품", "verbose_name_plural": "상품"},
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="photo",
            field=models.ImageField(blank=True, upload_to="mall/product/%Y/%m/%d"),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "정상"),
                    ("sold_out", "품절"),
                    ("obsolete", "단종"),
                    ("inactive", "비활성화"),
                ],
                default="inactive",
                max_length=10,
            ),
        ),
    ]
